[package]
name = "sys-dock"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[dependencies]
tauri = { version = "2.0", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.29"
wmi = "0.10"
raw-cpuid = "10"
get_if_addrs = "0.5"
image = "0.24"
base64 = "0.21"
windows = { version = "0.52", features = [
    "Win32_UI_Shell",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging"
] }

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

